Fix fail to start when LANG not valid
On Ubuntu 18.04 after install a LANG of en_AU was seen, which because it
lacked the .utf8 suffix does fail locale.setlocale thus;

>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'en_AU')
locale.Error: unsupported locale setting

Should not be treated as fatal.  Use en_US.utf8 instead.